socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  respect-rules: true
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  proxy-server-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
  fallback:
    - 1.1.1.1
    - 1.0.0.1
    
proxies:
proxy-providers:
  WS Akun ID:
    type: http
    path: "./WS Akun ID.yaml"
    url: https://raw.githubusercontent.com/LastExchange/Tunneling-Clash/refs/heads/main/Akun%20ID.yaml
    interval: 1200
  WS Akun SG:
    type: http
    path: "./WS Akun SG.yaml"
    url: https://raw.githubusercontent.com/LastExchange/Tunneling-Clash/refs/heads/main/Akun%20SG.yaml
    interval: 1200
  My Traffic: # Mengganti nama agar konsisten
    type: http
    path: "./My Traffic.yaml"
    url: https://raw.githubusercontent.com/LastExchange/Tunneling-Clash/refs/heads/main/My%20Traffic.yaml
    interval: 1200
    
rule-providers:
  RP Hiburan:
    type: http
    behavior: domain
    path: "./RP Streaming.yaml"
    url: https://raw.githubusercontent.com/LastExchange/Tunneling-Clash/refs/heads/main/RP%20Hiburan.yaml
    interval: 1200
    
proxy-groups:
  # Grup Pilihan Utama
  - name: LYCORIS
    type: select
    proxies:
      - FALLBACK
      - BEST-PING
      - LOAD-BALANCE
      - DIRECT

  # Grup Cadangan jika ada masalah
  - name: FALLBACK
    type: fallback
    url: https://www.gstatic.com/generate_204
    interval: 150 # Interval wajar
    use:
    - WS Akun ID
    - WS Akun SG

  # Grup Ping Terbaik untuk Gaming
  - name: BEST-PING
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 150 # Interval wajar
    tolerance: 50
    use:
    - WS Akun ID
    - WS Akun SG

  # Grup Load Balance untuk Streaming
  - name: LOAD-BALANCE
    type: load-balance
    strategy: consistent-hashing
    url: https://www.gstatic.com/generate_204
    interval: 200 # Interval lebih lama karena tidak butuh cek cepat
    use:
    - WS Akun ID
    - WS Akun SG
      
  # Grup Otomatis Default (Opsional tapi direkomendasikan)
  - name: My Traffic
    type: fallback
    url: https://www.gstatic.com/generate_204
    interval: 150 # Interval wajar
    use:
    - My Traffic

rules:
  - RULE-SET, RP Hiburan, My Traffic
  - MATCH, LYCORIS
